# Generated by Django 2.1.5 on 2019-02-16 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchedPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Name')),
                ('shortname', models.CharField(default=None, max_length=40, unique=True, verbose_name='Shortname')),
                ('publish_date', models.IntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(3000)], verbose_name='Year published')),
                ('last_fetch_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last data fetch')),
                ('last_modified_date', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='When data was changed after a fetch')),
                ('source_id', models.CharField(db_index=True, max_length=50, verbose_name='Source identifier')),
                ('source_url', models.CharField(max_length=255, verbose_name='Resource source URI')),
                ('change_hash', models.CharField(editable=False, max_length=32, verbose_name='Marker to detect data changes after a fetch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
