# Generated by Django 2.1.5 on 2019-02-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogsources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchedplatform',
            name='change_hash',
            field=models.CharField(max_length=32, verbose_name='Marker to detect data changes after a fetch'),
        ),
        migrations.AlterField(
            model_name='fetchedplatform',
            name='last_modified_date',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Last data modification'),
        ),
    ]
