# Generated by Django 2.1.5 on 2019-02-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogsources', '0002_auto_20190216_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchedplatform',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Flag to hide the item everywhere (including admin)'),
        ),
    ]
