# Generated by Django 2.1.7 on 2019-03-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogsources', '0002_auto_20190228_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchedgame',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='fetchedplatform',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='fetchedplatform',
            name='shortname',
            field=models.CharField(default=None, max_length=40, verbose_name='Shortname'),
        ),
    ]
