# Generated by Django 2.1.5 on 2019-02-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogsources', '0003_fetchedplatform_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchedplatform',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Hide the item (unwanted)'),
        ),
    ]
