# Generated by Django 2.1.5 on 2019-02-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogsources', '0004_auto_20190216_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchedplatform',
            name='hidden',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Item hidden'),
        ),
    ]
