# Generated by Django 2.2.9 on 2019-12-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogsources", "0004_auto_20190309_1320"),
    ]

    operations = [
        migrations.AddField(
            model_name="fetchedgame",
            name="last_sync_date",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True, verbose_name="Last synchronization"
            ),
        ),
    ]
