# Generated by Django 2.1.5 on 2019-02-16 10:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usergame_no_longer_owned'),
        ('catalogsources', '0005_auto_20190216_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchedGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Name')),
                ('publish_date', models.IntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(3000)], verbose_name='Year first published')),
                ('dlc_or_expansion', models.BooleanField(default=False, verbose_name='DLC/Expansion')),
                ('last_fetch_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last data fetch')),
                ('last_modified_date', models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Last data modification')),
                ('source_id', models.CharField(db_index=True, max_length=50, verbose_name='Source identifier')),
                ('source_url', models.CharField(max_length=255, verbose_name='Resource source URI')),
                ('change_hash', models.CharField(max_length=32, verbose_name='Marker to detect data changes after a fetch')),
                ('hidden', models.BooleanField(db_index=True, default=False, verbose_name='Item hidden')),
                ('parent_game', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogsources.FetchedGame')),
                ('platforms', models.ManyToManyField(to='core.Platform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
