# Generated by Django 2.1.5 on 2019-02-16 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogsources', '0007_auto_20190216_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchedgame',
            name='fg_game_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Game'),
        ),
        migrations.AlterField(
            model_name='fetchedplatform',
            name='fg_platform_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Platform'),
        ),
    ]
