# Generated by Django 2.1.7 on 2019-02-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogsources', '0008_auto_20190216_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchedgame',
            name='source_game_id',
            field=models.CharField(db_index=True, default=1, max_length=50, verbose_name='Source game identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fetchedplatform',
            name='source_platform_id',
            field=models.CharField(db_index=True, default=1, max_length=50, verbose_name='Source platform identifier'),
            preserve_default=False,
        ),
    ]
