# Generated by Django 2.1.7 on 2019-02-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogsources', '0009_auto_20190217_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchedgame',
            name='change_hash',
            field=models.CharField(max_length=32, verbose_name='Marker to detect data changes after fetch'),
        ),
        migrations.AlterField(
            model_name='fetchedplatform',
            name='change_hash',
            field=models.CharField(max_length=32, verbose_name='Marker to detect data changes after fetch'),
        ),
    ]
