# Generated by Django 2.1.7 on 2019-02-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogsources', '0010_auto_20190223_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fetchedplatform',
            old_name='fg_platform_id',
            new_name='fg_platform',
        ),
    ]
