# Generated by Django 2.1.7 on 2019-02-26 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogsources', '0011_auto_20190224_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetchedgame',
            name='last_fetch_date',
        ),
        migrations.RemoveField(
            model_name='fetchedplatform',
            name='last_fetch_date',
        ),
    ]
