version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout

      - run:
          command: make test
          working_directory: ~/project
          environment:
            BUILD_ENV: dev
