# Generated by Django 2.2.17 on 2020-11-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_game_name_for_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="cover",
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name="Cover filename"),
        ),
    ]
