# Generated by Django 2.2.17 on 2020-12-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_game_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platform",
            name="shortname",
            field=models.CharField(db_index=True, default=None, max_length=40, unique=True, verbose_name="Shortname"),
        ),
    ]
