# Generated by Django 2.2.28 on 2025-10-15 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_update_usergame_year_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='minutes_played',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minutes played'),
        ),
    ]
